require(shinydashboard)
library(shiny)
library(graphics)
library(shinydashboard)
library(ggplot2)
library(ggthemes)
library(party)
library(caret)
library(plotly)
library(curl)
library(RCurl)
library(e1071)
library(rpart)
library(tibble)
library(ranger)
library(leaflet)
library(dplyr)
library(here)
library(DT)
library(magrittr) # needs to be run every time you start R and want to use %>%
library(rvest)
library(dplyr)
library(idmodelr)
library(xml2)
library(readr)
library(shiny)
library(plotly)
library(shinydashboard)
library(shinydashboardPlus)
library(htmltools)
library(shinyWidgets)
library(quantmod)
library(ggplot2)
library(leaflet)
library(highcharter)
library(shiny)
library(graphics)
library(shinydashboard)
library(ggplot2)
library(ggthemes)
library(party)
library(caret)
library(plotly)
library(curl)
library(RCurl)
library(e1071)
library(rpart)
library(ranger)
library(leaflet)
library(dplyr)




